[simulation]
T = 12
h = 0.01
epsilon = 0.9999999999999999
infiniteMode = true
xPastExpression = "0"
yPastExpression = "2"

[constraint]
expression = "r - sqrt(max(abs(x) - R/2, 0)^2 + y^2)"
R = 0.8
r = 0.5
a = 0
b = 0

[trajectory]
xExpression = "2*sin(t)"
yExpression = "2*cos(t)"
alphaExpression = "t"

[metadata]
name = "Simulation Configuration"
description = "Delayed sweeping process simulation"
created = "2026-01-28T07:42:22.860Z"
